/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionLedgerRouteImport } from './routes/transaction-ledger'
import { Route as RechargeRouteImport } from './routes/recharge'
import { Route as DevModalsRouteImport } from './routes/dev-modals'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AccountInfoRouteImport } from './routes/account-info'
import { Route as IndexRouteImport } from './routes/index'

const TransactionLedgerRoute = TransactionLedgerRouteImport.update({
  id: '/transaction-ledger',
  path: '/transaction-ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const RechargeRoute = RechargeRouteImport.update({
  id: '/recharge',
  path: '/recharge',
  getParentRoute: () => rootRouteImport,
} as any)
const DevModalsRoute = DevModalsRouteImport.update({
  id: '/dev-modals',
  path: '/dev-modals',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountInfoRoute = AccountInfoRouteImport.update({
  id: '/account-info',
  path: '/account-info',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-info': typeof AccountInfoRoute
  '/dashboard': typeof DashboardRoute
  '/dev-modals': typeof DevModalsRoute
  '/recharge': typeof RechargeRoute
  '/transaction-ledger': typeof TransactionLedgerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-info': typeof AccountInfoRoute
  '/dashboard': typeof DashboardRoute
  '/dev-modals': typeof DevModalsRoute
  '/recharge': typeof RechargeRoute
  '/transaction-ledger': typeof TransactionLedgerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account-info': typeof AccountInfoRoute
  '/dashboard': typeof DashboardRoute
  '/dev-modals': typeof DevModalsRoute
  '/recharge': typeof RechargeRoute
  '/transaction-ledger': typeof TransactionLedgerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-info'
    | '/dashboard'
    | '/dev-modals'
    | '/recharge'
    | '/transaction-ledger'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-info'
    | '/dashboard'
    | '/dev-modals'
    | '/recharge'
    | '/transaction-ledger'
  id:
    | '__root__'
    | '/'
    | '/account-info'
    | '/dashboard'
    | '/dev-modals'
    | '/recharge'
    | '/transaction-ledger'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountInfoRoute: typeof AccountInfoRoute
  DashboardRoute: typeof DashboardRoute
  DevModalsRoute: typeof DevModalsRoute
  RechargeRoute: typeof RechargeRoute
  TransactionLedgerRoute: typeof TransactionLedgerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transaction-ledger': {
      id: '/transaction-ledger'
      path: '/transaction-ledger'
      fullPath: '/transaction-ledger'
      preLoaderRoute: typeof TransactionLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recharge': {
      id: '/recharge'
      path: '/recharge'
      fullPath: '/recharge'
      preLoaderRoute: typeof RechargeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-modals': {
      id: '/dev-modals'
      path: '/dev-modals'
      fullPath: '/dev-modals'
      preLoaderRoute: typeof DevModalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-info': {
      id: '/account-info'
      path: '/account-info'
      fullPath: '/account-info'
      preLoaderRoute: typeof AccountInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountInfoRoute: AccountInfoRoute,
  DashboardRoute: DashboardRoute,
  DevModalsRoute: DevModalsRoute,
  RechargeRoute: RechargeRoute,
  TransactionLedgerRoute: TransactionLedgerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
