/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionLedgerRouteImport } from './routes/transaction-ledger'
import { Route as StartRouteImport } from './routes/start'
import { Route as RechargeRouteImport } from './routes/recharge'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AccountInfoRouteImport } from './routes/account-info'
import { Route as IndexRouteImport } from './routes/index'

const TransactionLedgerRoute = TransactionLedgerRouteImport.update({
  id: '/transaction-ledger',
  path: '/transaction-ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const RechargeRoute = RechargeRouteImport.update({
  id: '/recharge',
  path: '/recharge',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountInfoRoute = AccountInfoRouteImport.update({
  id: '/account-info',
  path: '/account-info',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account-info': typeof AccountInfoRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/recharge': typeof RechargeRoute
  '/start': typeof StartRoute
  '/transaction-ledger': typeof TransactionLedgerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account-info': typeof AccountInfoRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/recharge': typeof RechargeRoute
  '/start': typeof StartRoute
  '/transaction-ledger': typeof TransactionLedgerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account-info': typeof AccountInfoRoute
  '/dashboard': typeof DashboardRoute
  '/login': typeof LoginRoute
  '/recharge': typeof RechargeRoute
  '/start': typeof StartRoute
  '/transaction-ledger': typeof TransactionLedgerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account-info'
    | '/dashboard'
    | '/login'
    | '/recharge'
    | '/start'
    | '/transaction-ledger'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account-info'
    | '/dashboard'
    | '/login'
    | '/recharge'
    | '/start'
    | '/transaction-ledger'
  id:
    | '__root__'
    | '/'
    | '/account-info'
    | '/dashboard'
    | '/login'
    | '/recharge'
    | '/start'
    | '/transaction-ledger'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountInfoRoute: typeof AccountInfoRoute
  DashboardRoute: typeof DashboardRoute
  LoginRoute: typeof LoginRoute
  RechargeRoute: typeof RechargeRoute
  StartRoute: typeof StartRoute
  TransactionLedgerRoute: typeof TransactionLedgerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transaction-ledger': {
      id: '/transaction-ledger'
      path: '/transaction-ledger'
      fullPath: '/transaction-ledger'
      preLoaderRoute: typeof TransactionLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recharge': {
      id: '/recharge'
      path: '/recharge'
      fullPath: '/recharge'
      preLoaderRoute: typeof RechargeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account-info': {
      id: '/account-info'
      path: '/account-info'
      fullPath: '/account-info'
      preLoaderRoute: typeof AccountInfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountInfoRoute: AccountInfoRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  RechargeRoute: RechargeRoute,
  StartRoute: StartRoute,
  TransactionLedgerRoute: TransactionLedgerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
